// Code generated by protoc-gen-go. DO NOT EDIT.
// source: registry.proto

package model

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ServiceInformation
type ServiceInformation struct {
	// id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// port
	Port uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	// address
	Address string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	// tags
	Tags []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	// metadata
	Metadata string `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// version
	Version              string   `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceInformation) Reset()         { *m = ServiceInformation{} }
func (m *ServiceInformation) String() string { return proto.CompactTextString(m) }
func (*ServiceInformation) ProtoMessage()    {}
func (*ServiceInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{0}
}

func (m *ServiceInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceInformation.Unmarshal(m, b)
}
func (m *ServiceInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceInformation.Marshal(b, m, deterministic)
}
func (m *ServiceInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceInformation.Merge(m, src)
}
func (m *ServiceInformation) XXX_Size() int {
	return xxx_messageInfo_ServiceInformation.Size(m)
}
func (m *ServiceInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceInformation.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceInformation proto.InternalMessageInfo

func (m *ServiceInformation) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ServiceInformation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceInformation) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ServiceInformation) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ServiceInformation) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ServiceInformation) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

func (m *ServiceInformation) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// RegisterServiceRequest
type RegisterServiceRequest struct {
	// id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// port
	Port uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	// address
	Address string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	// tags
	Tags []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	// metadata
	Metadata string `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// version
	Version              string   `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterServiceRequest) Reset()         { *m = RegisterServiceRequest{} }
func (m *RegisterServiceRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterServiceRequest) ProtoMessage()    {}
func (*RegisterServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{1}
}

func (m *RegisterServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterServiceRequest.Unmarshal(m, b)
}
func (m *RegisterServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterServiceRequest.Marshal(b, m, deterministic)
}
func (m *RegisterServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterServiceRequest.Merge(m, src)
}
func (m *RegisterServiceRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterServiceRequest.Size(m)
}
func (m *RegisterServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterServiceRequest proto.InternalMessageInfo

func (m *RegisterServiceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RegisterServiceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterServiceRequest) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *RegisterServiceRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *RegisterServiceRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *RegisterServiceRequest) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

func (m *RegisterServiceRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// RegisterServiceResponse
type RegisterServiceResponse struct {
	// message
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterServiceResponse) Reset()         { *m = RegisterServiceResponse{} }
func (m *RegisterServiceResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterServiceResponse) ProtoMessage()    {}
func (*RegisterServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{2}
}

func (m *RegisterServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterServiceResponse.Unmarshal(m, b)
}
func (m *RegisterServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterServiceResponse.Marshal(b, m, deterministic)
}
func (m *RegisterServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterServiceResponse.Merge(m, src)
}
func (m *RegisterServiceResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterServiceResponse.Size(m)
}
func (m *RegisterServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterServiceResponse proto.InternalMessageInfo

func (m *RegisterServiceResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// GetServiceRequest
type GetServiceRequest struct {
	// id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// version
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// tag
	Tag                  string   `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetServiceRequest) Reset()         { *m = GetServiceRequest{} }
func (m *GetServiceRequest) String() string { return proto.CompactTextString(m) }
func (*GetServiceRequest) ProtoMessage()    {}
func (*GetServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{3}
}

func (m *GetServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServiceRequest.Unmarshal(m, b)
}
func (m *GetServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServiceRequest.Marshal(b, m, deterministic)
}
func (m *GetServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServiceRequest.Merge(m, src)
}
func (m *GetServiceRequest) XXX_Size() int {
	return xxx_messageInfo_GetServiceRequest.Size(m)
}
func (m *GetServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetServiceRequest proto.InternalMessageInfo

func (m *GetServiceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetServiceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetServiceRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GetServiceRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

// GetServiceResponse
type GetServiceResponse struct {
	// message
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// service
	Service              *ServiceInformation `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetServiceResponse) Reset()         { *m = GetServiceResponse{} }
func (m *GetServiceResponse) String() string { return proto.CompactTextString(m) }
func (*GetServiceResponse) ProtoMessage()    {}
func (*GetServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{4}
}

func (m *GetServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServiceResponse.Unmarshal(m, b)
}
func (m *GetServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServiceResponse.Marshal(b, m, deterministic)
}
func (m *GetServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServiceResponse.Merge(m, src)
}
func (m *GetServiceResponse) XXX_Size() int {
	return xxx_messageInfo_GetServiceResponse.Size(m)
}
func (m *GetServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetServiceResponse proto.InternalMessageInfo

func (m *GetServiceResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetServiceResponse) GetService() *ServiceInformation {
	if m != nil {
		return m.Service
	}
	return nil
}

// ListServicesRequest
type ListServicesRequest struct {
	// name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// version
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// tag
	Tag                  string   `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListServicesRequest) Reset()         { *m = ListServicesRequest{} }
func (m *ListServicesRequest) String() string { return proto.CompactTextString(m) }
func (*ListServicesRequest) ProtoMessage()    {}
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{5}
}

func (m *ListServicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListServicesRequest.Unmarshal(m, b)
}
func (m *ListServicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListServicesRequest.Marshal(b, m, deterministic)
}
func (m *ListServicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListServicesRequest.Merge(m, src)
}
func (m *ListServicesRequest) XXX_Size() int {
	return xxx_messageInfo_ListServicesRequest.Size(m)
}
func (m *ListServicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListServicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListServicesRequest proto.InternalMessageInfo

func (m *ListServicesRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListServicesRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ListServicesRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

// ListServicesResponse
type ListServicesResponse struct {
	// message
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// services
	Services             []*ServiceInformation `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListServicesResponse) Reset()         { *m = ListServicesResponse{} }
func (m *ListServicesResponse) String() string { return proto.CompactTextString(m) }
func (*ListServicesResponse) ProtoMessage()    {}
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{6}
}

func (m *ListServicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListServicesResponse.Unmarshal(m, b)
}
func (m *ListServicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListServicesResponse.Marshal(b, m, deterministic)
}
func (m *ListServicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListServicesResponse.Merge(m, src)
}
func (m *ListServicesResponse) XXX_Size() int {
	return xxx_messageInfo_ListServicesResponse.Size(m)
}
func (m *ListServicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListServicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListServicesResponse proto.InternalMessageInfo

func (m *ListServicesResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ListServicesResponse) GetServices() []*ServiceInformation {
	if m != nil {
		return m.Services
	}
	return nil
}

// DeregisterServiceRequest
type DeregisterServiceRequest struct {
	// id
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeregisterServiceRequest) Reset()         { *m = DeregisterServiceRequest{} }
func (m *DeregisterServiceRequest) String() string { return proto.CompactTextString(m) }
func (*DeregisterServiceRequest) ProtoMessage()    {}
func (*DeregisterServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{7}
}

func (m *DeregisterServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeregisterServiceRequest.Unmarshal(m, b)
}
func (m *DeregisterServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeregisterServiceRequest.Marshal(b, m, deterministic)
}
func (m *DeregisterServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeregisterServiceRequest.Merge(m, src)
}
func (m *DeregisterServiceRequest) XXX_Size() int {
	return xxx_messageInfo_DeregisterServiceRequest.Size(m)
}
func (m *DeregisterServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeregisterServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeregisterServiceRequest proto.InternalMessageInfo

func (m *DeregisterServiceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// DeregisterServiceResponse
type DeregisterServiceResponse struct {
	// message
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeregisterServiceResponse) Reset()         { *m = DeregisterServiceResponse{} }
func (m *DeregisterServiceResponse) String() string { return proto.CompactTextString(m) }
func (*DeregisterServiceResponse) ProtoMessage()    {}
func (*DeregisterServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{8}
}

func (m *DeregisterServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeregisterServiceResponse.Unmarshal(m, b)
}
func (m *DeregisterServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeregisterServiceResponse.Marshal(b, m, deterministic)
}
func (m *DeregisterServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeregisterServiceResponse.Merge(m, src)
}
func (m *DeregisterServiceResponse) XXX_Size() int {
	return xxx_messageInfo_DeregisterServiceResponse.Size(m)
}
func (m *DeregisterServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeregisterServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeregisterServiceResponse proto.InternalMessageInfo

func (m *DeregisterServiceResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// PutValueRequest
type PutValueRequest struct {
	// key
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// value
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutValueRequest) Reset()         { *m = PutValueRequest{} }
func (m *PutValueRequest) String() string { return proto.CompactTextString(m) }
func (*PutValueRequest) ProtoMessage()    {}
func (*PutValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{9}
}

func (m *PutValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutValueRequest.Unmarshal(m, b)
}
func (m *PutValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutValueRequest.Marshal(b, m, deterministic)
}
func (m *PutValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutValueRequest.Merge(m, src)
}
func (m *PutValueRequest) XXX_Size() int {
	return xxx_messageInfo_PutValueRequest.Size(m)
}
func (m *PutValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutValueRequest proto.InternalMessageInfo

func (m *PutValueRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutValueRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// PutValueResponse
type PutValueResponse struct {
	// message
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutValueResponse) Reset()         { *m = PutValueResponse{} }
func (m *PutValueResponse) String() string { return proto.CompactTextString(m) }
func (*PutValueResponse) ProtoMessage()    {}
func (*PutValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{10}
}

func (m *PutValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutValueResponse.Unmarshal(m, b)
}
func (m *PutValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutValueResponse.Marshal(b, m, deterministic)
}
func (m *PutValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutValueResponse.Merge(m, src)
}
func (m *PutValueResponse) XXX_Size() int {
	return xxx_messageInfo_PutValueResponse.Size(m)
}
func (m *PutValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutValueResponse proto.InternalMessageInfo

func (m *PutValueResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// GetValueRequest
type GetValueRequest struct {
	// key
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetValueRequest) Reset()         { *m = GetValueRequest{} }
func (m *GetValueRequest) String() string { return proto.CompactTextString(m) }
func (*GetValueRequest) ProtoMessage()    {}
func (*GetValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{11}
}

func (m *GetValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValueRequest.Unmarshal(m, b)
}
func (m *GetValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValueRequest.Marshal(b, m, deterministic)
}
func (m *GetValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValueRequest.Merge(m, src)
}
func (m *GetValueRequest) XXX_Size() int {
	return xxx_messageInfo_GetValueRequest.Size(m)
}
func (m *GetValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetValueRequest proto.InternalMessageInfo

func (m *GetValueRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// GetValueResponse
type GetValueResponse struct {
	// message
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// value
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetValueResponse) Reset()         { *m = GetValueResponse{} }
func (m *GetValueResponse) String() string { return proto.CompactTextString(m) }
func (*GetValueResponse) ProtoMessage()    {}
func (*GetValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{12}
}

func (m *GetValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValueResponse.Unmarshal(m, b)
}
func (m *GetValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValueResponse.Marshal(b, m, deterministic)
}
func (m *GetValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValueResponse.Merge(m, src)
}
func (m *GetValueResponse) XXX_Size() int {
	return xxx_messageInfo_GetValueResponse.Size(m)
}
func (m *GetValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetValueResponse proto.InternalMessageInfo

func (m *GetValueResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetValueResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// ListKeysRequest
type ListKeysRequest struct {
	// prefix
	Prefix               string   `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListKeysRequest) Reset()         { *m = ListKeysRequest{} }
func (m *ListKeysRequest) String() string { return proto.CompactTextString(m) }
func (*ListKeysRequest) ProtoMessage()    {}
func (*ListKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{13}
}

func (m *ListKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListKeysRequest.Unmarshal(m, b)
}
func (m *ListKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListKeysRequest.Marshal(b, m, deterministic)
}
func (m *ListKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListKeysRequest.Merge(m, src)
}
func (m *ListKeysRequest) XXX_Size() int {
	return xxx_messageInfo_ListKeysRequest.Size(m)
}
func (m *ListKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListKeysRequest proto.InternalMessageInfo

func (m *ListKeysRequest) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

// ListKeysResponse
type ListKeysResponse struct {
	// message
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// keys
	Keys                 []string `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListKeysResponse) Reset()         { *m = ListKeysResponse{} }
func (m *ListKeysResponse) String() string { return proto.CompactTextString(m) }
func (*ListKeysResponse) ProtoMessage()    {}
func (*ListKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{14}
}

func (m *ListKeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListKeysResponse.Unmarshal(m, b)
}
func (m *ListKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListKeysResponse.Marshal(b, m, deterministic)
}
func (m *ListKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListKeysResponse.Merge(m, src)
}
func (m *ListKeysResponse) XXX_Size() int {
	return xxx_messageInfo_ListKeysResponse.Size(m)
}
func (m *ListKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListKeysResponse proto.InternalMessageInfo

func (m *ListKeysResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ListKeysResponse) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

// ListValuesRequest
type ListValuesRequest struct {
	// prefix
	Prefix               string   `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListValuesRequest) Reset()         { *m = ListValuesRequest{} }
func (m *ListValuesRequest) String() string { return proto.CompactTextString(m) }
func (*ListValuesRequest) ProtoMessage()    {}
func (*ListValuesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{15}
}

func (m *ListValuesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListValuesRequest.Unmarshal(m, b)
}
func (m *ListValuesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListValuesRequest.Marshal(b, m, deterministic)
}
func (m *ListValuesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListValuesRequest.Merge(m, src)
}
func (m *ListValuesRequest) XXX_Size() int {
	return xxx_messageInfo_ListValuesRequest.Size(m)
}
func (m *ListValuesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListValuesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListValuesRequest proto.InternalMessageInfo

func (m *ListValuesRequest) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

// ListValuesResponse
type ListValuesResponse struct {
	// message
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// values
	Values               map[string]string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListValuesResponse) Reset()         { *m = ListValuesResponse{} }
func (m *ListValuesResponse) String() string { return proto.CompactTextString(m) }
func (*ListValuesResponse) ProtoMessage()    {}
func (*ListValuesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{16}
}

func (m *ListValuesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListValuesResponse.Unmarshal(m, b)
}
func (m *ListValuesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListValuesResponse.Marshal(b, m, deterministic)
}
func (m *ListValuesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListValuesResponse.Merge(m, src)
}
func (m *ListValuesResponse) XXX_Size() int {
	return xxx_messageInfo_ListValuesResponse.Size(m)
}
func (m *ListValuesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListValuesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListValuesResponse proto.InternalMessageInfo

func (m *ListValuesResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ListValuesResponse) GetValues() map[string]string {
	if m != nil {
		return m.Values
	}
	return nil
}

// DeleteValueRequest
type DeleteValueRequest struct {
	// key
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteValueRequest) Reset()         { *m = DeleteValueRequest{} }
func (m *DeleteValueRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteValueRequest) ProtoMessage()    {}
func (*DeleteValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{17}
}

func (m *DeleteValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteValueRequest.Unmarshal(m, b)
}
func (m *DeleteValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteValueRequest.Marshal(b, m, deterministic)
}
func (m *DeleteValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteValueRequest.Merge(m, src)
}
func (m *DeleteValueRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteValueRequest.Size(m)
}
func (m *DeleteValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteValueRequest proto.InternalMessageInfo

func (m *DeleteValueRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// DeleteValueResponse
type DeleteValueResponse struct {
	// message
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteValueResponse) Reset()         { *m = DeleteValueResponse{} }
func (m *DeleteValueResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteValueResponse) ProtoMessage()    {}
func (*DeleteValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{18}
}

func (m *DeleteValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteValueResponse.Unmarshal(m, b)
}
func (m *DeleteValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteValueResponse.Marshal(b, m, deterministic)
}
func (m *DeleteValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteValueResponse.Merge(m, src)
}
func (m *DeleteValueResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteValueResponse.Size(m)
}
func (m *DeleteValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteValueResponse proto.InternalMessageInfo

func (m *DeleteValueResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ServiceInformation)(nil), "model.ServiceInformation")
	proto.RegisterType((*RegisterServiceRequest)(nil), "model.RegisterServiceRequest")
	proto.RegisterType((*RegisterServiceResponse)(nil), "model.RegisterServiceResponse")
	proto.RegisterType((*GetServiceRequest)(nil), "model.GetServiceRequest")
	proto.RegisterType((*GetServiceResponse)(nil), "model.GetServiceResponse")
	proto.RegisterType((*ListServicesRequest)(nil), "model.ListServicesRequest")
	proto.RegisterType((*ListServicesResponse)(nil), "model.ListServicesResponse")
	proto.RegisterType((*DeregisterServiceRequest)(nil), "model.DeregisterServiceRequest")
	proto.RegisterType((*DeregisterServiceResponse)(nil), "model.DeregisterServiceResponse")
	proto.RegisterType((*PutValueRequest)(nil), "model.PutValueRequest")
	proto.RegisterType((*PutValueResponse)(nil), "model.PutValueResponse")
	proto.RegisterType((*GetValueRequest)(nil), "model.GetValueRequest")
	proto.RegisterType((*GetValueResponse)(nil), "model.GetValueResponse")
	proto.RegisterType((*ListKeysRequest)(nil), "model.ListKeysRequest")
	proto.RegisterType((*ListKeysResponse)(nil), "model.ListKeysResponse")
	proto.RegisterType((*ListValuesRequest)(nil), "model.ListValuesRequest")
	proto.RegisterType((*ListValuesResponse)(nil), "model.ListValuesResponse")
	proto.RegisterMapType((map[string]string)(nil), "model.ListValuesResponse.ValuesEntry")
	proto.RegisterType((*DeleteValueRequest)(nil), "model.DeleteValueRequest")
	proto.RegisterType((*DeleteValueResponse)(nil), "model.DeleteValueResponse")
}

func init() { proto.RegisterFile("registry.proto", fileDescriptor_41af05d40a615591) }

var fileDescriptor_41af05d40a615591 = []byte{
	// 652 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x5d, 0x92, 0xb5, 0x2b, 0xb7, 0xb0, 0x76, 0xde, 0xb4, 0xa5, 0x41, 0x40, 0x65, 0x04, 0x1a,
	0x1f, 0x2a, 0xd2, 0xaa, 0x49, 0x0c, 0x69, 0x12, 0x82, 0xc1, 0x34, 0xc1, 0x03, 0x0a, 0x02, 0xf1,
	0x1a, 0x9a, 0xbb, 0x2a, 0x5a, 0x9b, 0x14, 0xdb, 0xad, 0xe8, 0xdf, 0xe0, 0x57, 0xf0, 0xc8, 0x03,
	0x3f, 0x10, 0x39, 0x71, 0x9c, 0x34, 0x49, 0xc9, 0xc4, 0x13, 0x6f, 0x76, 0x7c, 0xee, 0xb9, 0xe7,
	0xfa, 0xde, 0xe3, 0x16, 0xb6, 0x19, 0x8e, 0x03, 0x2e, 0xd8, 0x72, 0x30, 0x63, 0x91, 0x88, 0x48,
	0x63, 0x1a, 0xf9, 0x38, 0xa1, 0xbf, 0x0c, 0x20, 0x1f, 0x91, 0x2d, 0x82, 0x11, 0x5e, 0x84, 0x97,
	0x11, 0x9b, 0x7a, 0x22, 0x88, 0x42, 0xb2, 0x0d, 0x66, 0xe0, 0xdb, 0x46, 0xdf, 0x38, 0xbc, 0xe1,
	0x9a, 0x81, 0x4f, 0x08, 0x6c, 0x86, 0xde, 0x14, 0x6d, 0x33, 0xfe, 0x12, 0xaf, 0xe5, 0xb7, 0x59,
	0xc4, 0x84, 0x6d, 0xf5, 0x8d, 0xc3, 0x5b, 0x6e, 0xbc, 0x26, 0x36, 0x6c, 0x79, 0xbe, 0xcf, 0x90,
	0x73, 0x7b, 0x33, 0x86, 0xa6, 0x5b, 0x89, 0x16, 0xde, 0x98, 0xdb, 0x8d, 0xbe, 0x25, 0x19, 0xe4,
	0x9a, 0x38, 0xd0, 0x9a, 0xa2, 0xf0, 0x7c, 0x4f, 0x78, 0x76, 0x33, 0x86, 0xeb, 0xbd, 0x64, 0x5a,
	0x20, 0xe3, 0x41, 0x14, 0xda, 0x5b, 0x09, 0x93, 0xda, 0xd2, 0xdf, 0x06, 0xec, 0xbb, 0x71, 0x31,
	0xc8, 0x94, 0x74, 0x17, 0xbf, 0xcd, 0x91, 0x8b, 0xff, 0x5a, 0xf6, 0x10, 0x0e, 0x4a, 0xaa, 0xf9,
	0x2c, 0x0a, 0x39, 0xca, 0xa0, 0x29, 0x72, 0xee, 0x8d, 0x51, 0x69, 0x4f, 0xb7, 0x74, 0x04, 0x3b,
	0xe7, 0x28, 0xfe, 0xa1, 0xca, 0x9c, 0x0e, 0x6b, 0x45, 0x07, 0xe9, 0x82, 0x25, 0xbc, 0xb1, 0xaa,
	0x53, 0x2e, 0xe9, 0x08, 0x48, 0x3e, 0x49, 0x9d, 0x28, 0x32, 0x84, 0x2d, 0x9e, 0x80, 0x63, 0x96,
	0xf6, 0x51, 0x6f, 0x10, 0x0f, 0xd3, 0xa0, 0x3c, 0x48, 0x6e, 0x8a, 0xa4, 0x9f, 0x60, 0xf7, 0x7d,
	0xc0, 0xd3, 0x2c, 0x3c, 0xad, 0x25, 0xd5, 0x6e, 0x54, 0x6b, 0x37, 0x2b, 0xb5, 0x5b, 0x99, 0xf6,
	0x31, 0xec, 0xad, 0xd2, 0xd6, 0xaa, 0x3f, 0x86, 0x96, 0xd2, 0x24, 0x9b, 0x6d, 0xfd, 0x5d, 0xbe,
	0x86, 0xd2, 0xc7, 0x60, 0x9f, 0x21, 0xbb, 0xd6, 0xd8, 0xd1, 0x63, 0xe8, 0x55, 0x60, 0x6b, 0x9b,
	0x7d, 0x02, 0x9d, 0x0f, 0x73, 0xf1, 0xd9, 0x9b, 0xcc, 0x35, 0x73, 0x17, 0xac, 0x2b, 0x5c, 0x2a,
	0xa0, 0x5c, 0x92, 0x3d, 0x68, 0x2c, 0x24, 0x42, 0x5d, 0x4d, 0xb2, 0xa1, 0x4f, 0xa1, 0x9b, 0x85,
	0xd6, 0x26, 0xba, 0x0f, 0x9d, 0x73, 0xac, 0x49, 0x44, 0x5f, 0x41, 0x37, 0x03, 0xd5, 0xde, 0x6a,
	0xb5, 0xac, 0x47, 0xd0, 0x91, 0xdd, 0x79, 0x87, 0x4b, 0xdd, 0xf0, 0x7d, 0x68, 0xce, 0x18, 0x5e,
	0x06, 0xdf, 0x15, 0x83, 0xda, 0xd1, 0x97, 0xd0, 0xcd, 0xa0, 0xb5, 0xe9, 0x08, 0x6c, 0x5e, 0xe1,
	0x92, 0xdb, 0x66, 0x62, 0x4b, 0xb9, 0xa6, 0x4f, 0x60, 0x47, 0x32, 0xc4, 0x8a, 0x6b, 0xd3, 0xfd,
	0x34, 0x80, 0xe4, 0xd1, 0xb5, 0x19, 0x4f, 0xa1, 0x19, 0xd7, 0x94, 0xe4, 0x6c, 0x1f, 0x3d, 0x50,
	0x43, 0x53, 0x26, 0x19, 0x24, 0xdb, 0x37, 0xa1, 0x60, 0x4b, 0x57, 0x05, 0x39, 0x27, 0xd0, 0xce,
	0x7d, 0xbe, 0x6e, 0x5f, 0x5f, 0x98, 0xcf, 0x0d, 0xfa, 0x10, 0xc8, 0x19, 0x4e, 0x50, 0x60, 0x4d,
	0xc3, 0x9e, 0xc1, 0xee, 0x0a, 0xae, 0xae, 0xa4, 0xa3, 0x1f, 0x0d, 0x68, 0xb9, 0xea, 0x57, 0x81,
	0xb8, 0xd0, 0x29, 0x3c, 0x4f, 0xe4, 0x8e, 0x2a, 0xb1, 0xfa, 0xb1, 0x75, 0xee, 0xae, 0x3b, 0x4e,
	0x12, 0xd3, 0x0d, 0xf2, 0x1a, 0x20, 0x7b, 0x58, 0x88, 0xad, 0xf0, 0xa5, 0x07, 0xcd, 0xe9, 0x55,
	0x9c, 0x68, 0x92, 0x0b, 0xb8, 0x99, 0x77, 0x38, 0x71, 0x72, 0x17, 0x5f, 0x78, 0x4d, 0x9c, 0xdb,
	0x95, 0x67, 0x9a, 0xea, 0x0b, 0xec, 0x94, 0x7c, 0x49, 0xee, 0xa9, 0x98, 0x75, 0xee, 0x76, 0xfa,
	0xeb, 0x01, 0x9a, 0xf9, 0x14, 0x5a, 0xa9, 0xff, 0xc8, 0xbe, 0xc2, 0x17, 0xbc, 0xec, 0x1c, 0x94,
	0xbe, 0xe7, 0xc3, 0x53, 0xaf, 0xe9, 0xf0, 0x82, 0x43, 0x75, 0x78, 0xd1, 0x94, 0x49, 0x78, 0xea,
	0x1d, 0x1d, 0x5e, 0xf0, 0x9d, 0x0e, 0x2f, 0x9a, 0x2c, 0x69, 0x53, 0x36, 0xc5, 0xba, 0x4d, 0x25,
	0x2f, 0xe9, 0x36, 0x95, 0x47, 0x9e, 0x6e, 0x90, 0xb7, 0xd0, 0xce, 0x4d, 0x1f, 0xe9, 0xe9, 0x4b,
	0x2b, 0x4e, 0xae, 0xe3, 0x54, 0x1d, 0xa5, 0x3c, 0x5f, 0x9b, 0xf1, 0xdf, 0x93, 0xe1, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xe9, 0xc3, 0xc1, 0x54, 0xb0, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RegistryClient is the client API for Registry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegistryClient interface {
	// RegisterService 能將一個新的服務註冊到服務庫中，並且提供給其他服務使用。
	RegisterService(ctx context.Context, in *RegisterServiceRequest, opts ...grpc.CallOption) (*RegisterServiceResponse, error)
	// GetService 可以從負載平衡中取得一個可用的服務。
	GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*GetServiceResponse, error)
	// ListServices 能夠列出所有可用（或是包含不可用）的服務。
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	// DeregisterService 會將一個指定的服務從服務庫中移除，讓中央服務庫不再追蹤該服務。
	DeregisterService(ctx context.Context, in *DeregisterServiceRequest, opts ...grpc.CallOption) (*DeregisterServiceResponse, error)
	// PutValue 能夠將一個指定的鍵值組放入中央服務庫內共享給其他服務存取。
	PutValue(ctx context.Context, in *PutValueRequest, opts ...grpc.CallOption) (*PutValueResponse, error)
	// GetValue 可以取得一個位於中央服務庫的鍵值組內容。
	GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*GetValueResponse, error)
	// ListKeys 能列出位於中央服務庫內所有（或是指定前輟）的鍵名。
	ListKeys(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*ListKeysResponse, error)
	// ListValues 能列出位於中央服務庫內所有（或是指定前輟）的鍵值組資料。
	ListValues(ctx context.Context, in *ListValuesRequest, opts ...grpc.CallOption) (*ListValuesResponse, error)
	// DeleteValue 會移除中央服務庫內的指定鍵值組資料。
	DeleteValue(ctx context.Context, in *DeleteValueRequest, opts ...grpc.CallOption) (*DeleteValueResponse, error)
}

type registryClient struct {
	cc *grpc.ClientConn
}

func NewRegistryClient(cc *grpc.ClientConn) RegistryClient {
	return &registryClient{cc}
}

func (c *registryClient) RegisterService(ctx context.Context, in *RegisterServiceRequest, opts ...grpc.CallOption) (*RegisterServiceResponse, error) {
	out := new(RegisterServiceResponse)
	err := c.cc.Invoke(ctx, "/model.Registry/RegisterService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*GetServiceResponse, error) {
	out := new(GetServiceResponse)
	err := c.cc.Invoke(ctx, "/model.Registry/GetService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, "/model.Registry/ListServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) DeregisterService(ctx context.Context, in *DeregisterServiceRequest, opts ...grpc.CallOption) (*DeregisterServiceResponse, error) {
	out := new(DeregisterServiceResponse)
	err := c.cc.Invoke(ctx, "/model.Registry/DeregisterService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) PutValue(ctx context.Context, in *PutValueRequest, opts ...grpc.CallOption) (*PutValueResponse, error) {
	out := new(PutValueResponse)
	err := c.cc.Invoke(ctx, "/model.Registry/PutValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*GetValueResponse, error) {
	out := new(GetValueResponse)
	err := c.cc.Invoke(ctx, "/model.Registry/GetValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) ListKeys(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*ListKeysResponse, error) {
	out := new(ListKeysResponse)
	err := c.cc.Invoke(ctx, "/model.Registry/ListKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) ListValues(ctx context.Context, in *ListValuesRequest, opts ...grpc.CallOption) (*ListValuesResponse, error) {
	out := new(ListValuesResponse)
	err := c.cc.Invoke(ctx, "/model.Registry/ListValues", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) DeleteValue(ctx context.Context, in *DeleteValueRequest, opts ...grpc.CallOption) (*DeleteValueResponse, error) {
	out := new(DeleteValueResponse)
	err := c.cc.Invoke(ctx, "/model.Registry/DeleteValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryServer is the server API for Registry service.
type RegistryServer interface {
	// RegisterService 能將一個新的服務註冊到服務庫中，並且提供給其他服務使用。
	RegisterService(context.Context, *RegisterServiceRequest) (*RegisterServiceResponse, error)
	// GetService 可以從負載平衡中取得一個可用的服務。
	GetService(context.Context, *GetServiceRequest) (*GetServiceResponse, error)
	// ListServices 能夠列出所有可用（或是包含不可用）的服務。
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	// DeregisterService 會將一個指定的服務從服務庫中移除，讓中央服務庫不再追蹤該服務。
	DeregisterService(context.Context, *DeregisterServiceRequest) (*DeregisterServiceResponse, error)
	// PutValue 能夠將一個指定的鍵值組放入中央服務庫內共享給其他服務存取。
	PutValue(context.Context, *PutValueRequest) (*PutValueResponse, error)
	// GetValue 可以取得一個位於中央服務庫的鍵值組內容。
	GetValue(context.Context, *GetValueRequest) (*GetValueResponse, error)
	// ListKeys 能列出位於中央服務庫內所有（或是指定前輟）的鍵名。
	ListKeys(context.Context, *ListKeysRequest) (*ListKeysResponse, error)
	// ListValues 能列出位於中央服務庫內所有（或是指定前輟）的鍵值組資料。
	ListValues(context.Context, *ListValuesRequest) (*ListValuesResponse, error)
	// DeleteValue 會移除中央服務庫內的指定鍵值組資料。
	DeleteValue(context.Context, *DeleteValueRequest) (*DeleteValueResponse, error)
}

func RegisterRegistryServer(s *grpc.Server, srv RegistryServer) {
	s.RegisterService(&_Registry_serviceDesc, srv)
}

func _Registry_RegisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).RegisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Registry/RegisterService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).RegisterService(ctx, req.(*RegisterServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_GetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).GetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Registry/GetService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).GetService(ctx, req.(*GetServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Registry/ListServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_DeregisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).DeregisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Registry/DeregisterService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).DeregisterService(ctx, req.(*DeregisterServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_PutValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).PutValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Registry/PutValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).PutValue(ctx, req.(*PutValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Registry/GetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).GetValue(ctx, req.(*GetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_ListKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).ListKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Registry/ListKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).ListKeys(ctx, req.(*ListKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_ListValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).ListValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Registry/ListValues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).ListValues(ctx, req.(*ListValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_DeleteValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).DeleteValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Registry/DeleteValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).DeleteValue(ctx, req.(*DeleteValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Registry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.Registry",
	HandlerType: (*RegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterService",
			Handler:    _Registry_RegisterService_Handler,
		},
		{
			MethodName: "GetService",
			Handler:    _Registry_GetService_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _Registry_ListServices_Handler,
		},
		{
			MethodName: "DeregisterService",
			Handler:    _Registry_DeregisterService_Handler,
		},
		{
			MethodName: "PutValue",
			Handler:    _Registry_PutValue_Handler,
		},
		{
			MethodName: "GetValue",
			Handler:    _Registry_GetValue_Handler,
		},
		{
			MethodName: "ListKeys",
			Handler:    _Registry_ListKeys_Handler,
		},
		{
			MethodName: "ListValues",
			Handler:    _Registry_ListValues_Handler,
		},
		{
			MethodName: "DeleteValue",
			Handler:    _Registry_DeleteValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "registry.proto",
}
