// Code generated by protoc-gen-go. DO NOT EDIT.
// source: registry.proto

package model

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ServiceInformation
type ServiceInformation struct {
	// id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// port
	Port uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	// address
	Address string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	// tags
	Tags []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	// metadata
	Metadata string `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// version
	Version              string   `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceInformation) Reset()         { *m = ServiceInformation{} }
func (m *ServiceInformation) String() string { return proto.CompactTextString(m) }
func (*ServiceInformation) ProtoMessage()    {}
func (*ServiceInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{0}
}

func (m *ServiceInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceInformation.Unmarshal(m, b)
}
func (m *ServiceInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceInformation.Marshal(b, m, deterministic)
}
func (m *ServiceInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceInformation.Merge(m, src)
}
func (m *ServiceInformation) XXX_Size() int {
	return xxx_messageInfo_ServiceInformation.Size(m)
}
func (m *ServiceInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceInformation.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceInformation proto.InternalMessageInfo

func (m *ServiceInformation) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ServiceInformation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceInformation) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ServiceInformation) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ServiceInformation) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ServiceInformation) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

func (m *ServiceInformation) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// GetServiceRequest
type GetServiceRequest struct {
	// name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// version
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// tag
	Tag                  string   `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetServiceRequest) Reset()         { *m = GetServiceRequest{} }
func (m *GetServiceRequest) String() string { return proto.CompactTextString(m) }
func (*GetServiceRequest) ProtoMessage()    {}
func (*GetServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{1}
}

func (m *GetServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServiceRequest.Unmarshal(m, b)
}
func (m *GetServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServiceRequest.Marshal(b, m, deterministic)
}
func (m *GetServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServiceRequest.Merge(m, src)
}
func (m *GetServiceRequest) XXX_Size() int {
	return xxx_messageInfo_GetServiceRequest.Size(m)
}
func (m *GetServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetServiceRequest proto.InternalMessageInfo

func (m *GetServiceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetServiceRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GetServiceRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

// GetServiceResponse
type GetServiceResponse struct {
	// message
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// service
	Service              *ServiceInformation `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetServiceResponse) Reset()         { *m = GetServiceResponse{} }
func (m *GetServiceResponse) String() string { return proto.CompactTextString(m) }
func (*GetServiceResponse) ProtoMessage()    {}
func (*GetServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{2}
}

func (m *GetServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServiceResponse.Unmarshal(m, b)
}
func (m *GetServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServiceResponse.Marshal(b, m, deterministic)
}
func (m *GetServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServiceResponse.Merge(m, src)
}
func (m *GetServiceResponse) XXX_Size() int {
	return xxx_messageInfo_GetServiceResponse.Size(m)
}
func (m *GetServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetServiceResponse proto.InternalMessageInfo

func (m *GetServiceResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetServiceResponse) GetService() *ServiceInformation {
	if m != nil {
		return m.Service
	}
	return nil
}

// ListServicesRequest
type ListServicesRequest struct {
	// name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// version
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// tag
	Tag                  string   `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListServicesRequest) Reset()         { *m = ListServicesRequest{} }
func (m *ListServicesRequest) String() string { return proto.CompactTextString(m) }
func (*ListServicesRequest) ProtoMessage()    {}
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{3}
}

func (m *ListServicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListServicesRequest.Unmarshal(m, b)
}
func (m *ListServicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListServicesRequest.Marshal(b, m, deterministic)
}
func (m *ListServicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListServicesRequest.Merge(m, src)
}
func (m *ListServicesRequest) XXX_Size() int {
	return xxx_messageInfo_ListServicesRequest.Size(m)
}
func (m *ListServicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListServicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListServicesRequest proto.InternalMessageInfo

func (m *ListServicesRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListServicesRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ListServicesRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

// ListServicesResponse
type ListServicesResponse struct {
	// message
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// services
	Services             []*ServiceInformation `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListServicesResponse) Reset()         { *m = ListServicesResponse{} }
func (m *ListServicesResponse) String() string { return proto.CompactTextString(m) }
func (*ListServicesResponse) ProtoMessage()    {}
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{4}
}

func (m *ListServicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListServicesResponse.Unmarshal(m, b)
}
func (m *ListServicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListServicesResponse.Marshal(b, m, deterministic)
}
func (m *ListServicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListServicesResponse.Merge(m, src)
}
func (m *ListServicesResponse) XXX_Size() int {
	return xxx_messageInfo_ListServicesResponse.Size(m)
}
func (m *ListServicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListServicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListServicesResponse proto.InternalMessageInfo

func (m *ListServicesResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ListServicesResponse) GetServices() []*ServiceInformation {
	if m != nil {
		return m.Services
	}
	return nil
}

func init() {
	proto.RegisterType((*ServiceInformation)(nil), "model.ServiceInformation")
	proto.RegisterType((*GetServiceRequest)(nil), "model.GetServiceRequest")
	proto.RegisterType((*GetServiceResponse)(nil), "model.GetServiceResponse")
	proto.RegisterType((*ListServicesRequest)(nil), "model.ListServicesRequest")
	proto.RegisterType((*ListServicesResponse)(nil), "model.ListServicesResponse")
}

func init() { proto.RegisterFile("registry.proto", fileDescriptor_41af05d40a615591) }

var fileDescriptor_41af05d40a615591 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x4f, 0x4e, 0xeb, 0x30,
	0x10, 0x87, 0x5f, 0x92, 0xfe, 0x9d, 0x07, 0x15, 0x0c, 0x2c, 0xdc, 0xb0, 0xa9, 0xb2, 0xea, 0xaa,
	0x8b, 0x56, 0x9c, 0x80, 0x05, 0xaa, 0xc4, 0x2a, 0x15, 0x07, 0x30, 0xcd, 0x10, 0x59, 0x22, 0x71,
	0xf1, 0x98, 0x4a, 0x5c, 0x85, 0x53, 0x70, 0x44, 0x64, 0x37, 0x2e, 0xa9, 0x5a, 0xc1, 0x86, 0xdd,
	0x8c, 0xfd, 0xcb, 0x97, 0xcf, 0x63, 0xc3, 0xc8, 0x50, 0xa9, 0xd8, 0x9a, 0xf7, 0xd9, 0xc6, 0x68,
	0xab, 0xb1, 0x5b, 0xe9, 0x82, 0x5e, 0xb2, 0xcf, 0x08, 0x70, 0x45, 0x66, 0xab, 0xd6, 0xb4, 0xac,
	0x9f, 0xb5, 0xa9, 0xa4, 0x55, 0xba, 0xc6, 0x11, 0xc4, 0xaa, 0x10, 0xd1, 0x24, 0x9a, 0x0e, 0xf3,
	0x58, 0x15, 0x88, 0xd0, 0xa9, 0x65, 0x45, 0x22, 0xf6, 0x2b, 0xbe, 0x76, 0x6b, 0x1b, 0x6d, 0xac,
	0x48, 0x26, 0xd1, 0xf4, 0x3c, 0xf7, 0x35, 0x0a, 0xe8, 0xcb, 0xa2, 0x30, 0xc4, 0x2c, 0x3a, 0x3e,
	0x1a, 0x5a, 0x97, 0xb6, 0xb2, 0x64, 0xd1, 0x9d, 0x24, 0x8e, 0xe0, 0x6a, 0x4c, 0x61, 0x50, 0x91,
	0x95, 0x85, 0xb4, 0x52, 0xf4, 0x7c, 0x7c, 0xdf, 0x3b, 0xd2, 0x96, 0x0c, 0x2b, 0x5d, 0x8b, 0xfe,
	0x8e, 0xd4, 0xb4, 0xd9, 0x0a, 0x2e, 0xef, 0xc9, 0x36, 0xd2, 0x39, 0xbd, 0xbe, 0x11, 0xdb, 0xbd,
	0x60, 0xd4, 0x12, 0x6c, 0x21, 0xe2, 0x03, 0x04, 0x5e, 0x40, 0x62, 0x65, 0xe9, 0xcd, 0x87, 0xb9,
	0x2b, 0xb3, 0x35, 0x60, 0x1b, 0xca, 0x1b, 0x5d, 0xb3, 0x27, 0x54, 0xc4, 0x2c, 0xcb, 0x00, 0x0e,
	0x2d, 0x2e, 0xa0, 0xcf, 0xbb, 0xb0, 0x3f, 0xe8, 0xff, 0xf9, 0x78, 0xe6, 0x07, 0x3a, 0x3b, 0x1e,
	0x66, 0x1e, 0x92, 0xd9, 0x23, 0x5c, 0x3d, 0x28, 0x0e, 0x7f, 0xe1, 0xbf, 0x72, 0x2f, 0xe1, 0xfa,
	0x10, 0xfb, 0xab, 0xfd, 0x2d, 0x0c, 0x1a, 0x27, 0x77, 0x4f, 0xc9, 0xcf, 0xfa, 0xfb, 0xe8, 0xfc,
	0x23, 0x82, 0x41, 0xde, 0x3c, 0x23, 0xbc, 0x03, 0xf8, 0x9e, 0x18, 0x8a, 0xe6, 0xfb, 0xa3, 0x9b,
	0x49, 0xc7, 0x27, 0x76, 0x76, 0x82, 0xd9, 0x3f, 0x5c, 0xc2, 0x59, 0x5b, 0x1d, 0xd3, 0x26, 0x7c,
	0x62, 0x4c, 0xe9, 0xcd, 0xc9, 0xbd, 0x80, 0x7a, 0xea, 0xf9, 0x77, 0xbd, 0xf8, 0x0a, 0x00, 0x00,
	0xff, 0xff, 0x8c, 0xd8, 0x47, 0xd9, 0xe9, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RegistryClient is the client API for Registry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegistryClient interface {
	// GetService 可以從負載平衡中取得一個可用的服務。
	GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*GetServiceResponse, error)
	// ListServices 能夠列出所有可用（或是包含不可用）的服務。
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
}

type registryClient struct {
	cc *grpc.ClientConn
}

func NewRegistryClient(cc *grpc.ClientConn) RegistryClient {
	return &registryClient{cc}
}

func (c *registryClient) GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*GetServiceResponse, error) {
	out := new(GetServiceResponse)
	err := c.cc.Invoke(ctx, "/model.Registry/GetService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, "/model.Registry/ListServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryServer is the server API for Registry service.
type RegistryServer interface {
	// GetService 可以從負載平衡中取得一個可用的服務。
	GetService(context.Context, *GetServiceRequest) (*GetServiceResponse, error)
	// ListServices 能夠列出所有可用（或是包含不可用）的服務。
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
}

func RegisterRegistryServer(s *grpc.Server, srv RegistryServer) {
	s.RegisterService(&_Registry_serviceDesc, srv)
}

func _Registry_GetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).GetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Registry/GetService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).GetService(ctx, req.(*GetServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Registry/ListServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Registry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.Registry",
	HandlerType: (*RegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetService",
			Handler:    _Registry_GetService_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _Registry_ListServices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "registry.proto",
}
